# Generated by Django 5.0.7 on 2024-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_mood', '0003_playlistgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'liked_songs',
                'managed': False,
            },
        ),
    ]
